name = "voxel-strike-asia-2"
main = "src/workers/router.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "LEADERBOARD"
id      = "4c171c9c5515419c8d93c4b86c3b4154"
preview_id = "51334660d0e642269b53b51d2dd4e10f"

[[kv_namespaces]]
binding = "SESSIONS"
id      = "19e5e273e99941fbb963300e56dbdf9e"
preview_id = "cd6625820745452ab9debf42fb0c836a"

[[kv_namespaces]]
binding = "ROOMS"
id      = "a68a11044ba2442596bfd5484195277e"
preview_id = "5e2f90cfcbd547639a16a6c608de9789"

[vars]
GAME_VERSION         = "1.0.0"
MAX_PLAYERS_PER_ROOM = "20"
SERVER_ID            = "asia-2"
SERVER_REGION        = "Tokyo"
ROUND_DURATION_SEC   = "300"
BOT_COUNT            = "9"
